#!/usr/bin/env bash

function _digitalocean_profile {
  local shome="${_digitalocean_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  PATH="$shome/bin:$shome/exec:$PATH"

  DOCTL_VERSION='1.7.0'

  if [[ -f "$BOARD_PATH/.config/doctl/config.yaml" ]]; then
    export DIGITALOCEAN_TOKEN="$(cat "$BOARD_PATH/.config/doctl/config.yaml" 2>/dev/null | awk '$1 == "access-token:" { print $2 }' || true)"
  fi
}

_digitalocean_profile
