#!/usr/bin/env bash

function _digitalocean_profile {
  local shome="${_digitalocean_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  PATH="$shome/bin:$shome/exec:$PATH"

  DOCTL_VERSION='1.7.0'
}

_digitalocean_profile
