#!/usr/bin/env bash

function _digitalocean_profile {
  local shome="${_digitalocean_home:="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  PATH="$shome/bin:$PATH"
}

_digitalocean_profile
