#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_doctl="$(doctl version 2>/dev/null | awk '$1 == "doctl" {print $3}' | cut -d- -f1 || true)"
  jq -n --arg doctl "$ver_doctl" '{doctl: $doctl}'
}

version "$@"
