#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_digitalocean="0.0.1"
  jq -n --arg digitalocean "$ver_digitalocean" '{digitalocean: $digitalocean}'
}

version "$@"
